version: 2

references:
  cache-options: &cache-options
    key: package-cache-{{ checksum "package.json" }}

jobs:
  build:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: npm-install
          command: npm install
      - save_cache:
          <<: *cache-options
          paths:
            - ./node_modules

  test:
    docker:
      - image: circleci/node:12
    steps:
      - checkout
      - restore_cache:
          <<: *cache-options
      - run:
          name: linter
          command: npm run lint
      - run:
          name: test
          command: ./node_modules/.bin/jest --ci

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
